<?php

namespace App\Modules\Notifications\Enums;

enum NotificationEvent: string
{
    case LEAD_DEAL = 'LEAD_DEAL';
    case PROJECT_ACTIVATED = 'PROJECT_ACTIVATED';
    
    case TASK_ASSIGNED = 'TASK_ASSIGNED';
    case TASK_REASSIGNED = 'TASK_REASSIGNED';
    case TASK_REVISION_REQUESTED = 'TASK_REVISION_REQUESTED';
    
    case ENTRY_SUBMITTED = 'ENTRY_SUBMITTED';
    case ENTRY_APPROVED = 'ENTRY_APPROVED';
    
    case AUDIT_SCHEDULED = 'AUDIT_SCHEDULED';
    case AUDIT_RESCHEDULED = 'AUDIT_RESCHEDULED';
    case AUDIT_SUBMITTED = 'AUDIT_SUBMITTED';
    case AUDIT_REVISION_REQUESTED = 'AUDIT_REVISION_REQUESTED';
    case AUDIT_APPROVED = 'AUDIT_APPROVED';
    
    case INVOICE_PUBLISHED = 'INVOICE_PUBLISHED';
    case PAYMENT_RECORDED = 'PAYMENT_RECORDED';
    case PAYMENT_VERIFIED = 'PAYMENT_VERIFIED';
    case PAYMENT_REJECTED = 'PAYMENT_REJECTED';
    case GOVERNMENT_INVOICE_AVAILABLE = 'GOVERNMENT_INVOICE_AVAILABLE';
    
    case CERTIFICATE_ISSUED = 'CERTIFICATE_ISSUED';
    
    case PROJECT_COMPLETED = 'PROJECT_COMPLETED';
    case PROJECT_CANCELLED = 'PROJECT_CANCELLED';
    case PROJECT_REOPENED = 'PROJECT_REOPENED';
    
    case DEADLINE_APPROACHING = 'DEADLINE_APPROACHING';
    case DEADLINE_OVERDUE = 'DEADLINE_OVERDUE';
}
